import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.*;

import java.sql.*;
import java.time.LocalDate;
import javax.imageio.ImageIO;
public class GenerateGradeSheet extends javax.swing.JInternalFrame {

    //Database components
    Connection con;
    PreparedStatement pst, pst1, pst2;
    ResultSet rs, rs1, rs2;
    
    
    String enteredRegID;
    
    //variables that store the fetched data
    String orgName;
    String orgAddress;
    String stdName;
    String fName;
    String lName;
    String stdDOB;
    String yearBS;
    String yearAD;
    String fetchedClass;
    String gNepali;
    String gEnglish;
    String gMaths;
    String gScience;
    String gDrawing;
    String gSerofero;
    String gHealth;
    String gSocial;
    String gLocalSubject;
    String remark;
    String ogpa;
    
    
    //also the logo of organization
    
    
    //variable that is used to store the current data 
    LocalDate localDate = LocalDate.now();
    String myDate = localDate.toString();
    
    
    //Creating object of different classes eg. ECD, class 1, class 2 and so on to directly put the fetched values
    ClassECDGradeSheet ecdSheet = new ClassECDGradeSheet();
    Class1GradeSheet oneSheet = new Class1GradeSheet();
    Class2GradeSheet twoSheet = new Class2GradeSheet();
    Class3GradeSheet threeSheet = new Class3GradeSheet();
    Class4GradeSheet fourSheet = new Class4GradeSheet();
    Class5GradeSheet fiveSheet = new Class5GradeSheet();
    Class6GradeSheet sixSheet = new Class6GradeSheet();
    Class7GradeSheet sevenSheet = new Class7GradeSheet();
    Class8GradeSheet eightSheet = new Class8GradeSheet();
    
//    //Creating object of login page inorder to access the organization's details
//    LandingPage lpg = new LandingPage();
//    
//    //the following variable is used to store the user's login email
//    String loginMail =  lpg.userEmail.getText();
    Dashboard db2 = new Dashboard();
    String orgBase = db2.jLabel7.getText();
    
    //following variables store the fetched organizational details
    String fetchedOrgName;
    String fetchedOrgAddress;
    
    //logged in email
    String loggedInMail = LandingPage.enteredUserMail;
    
    public GenerateGradeSheet() {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui =  (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        connectToDatabase();
        
    }
    
    public void connectToDatabase(){
        
        try{
            String url = "jdbc:mysql://localhost:3306/firstproject";
            String username = "root";
            String password = "seeuagain";
            con = DriverManager.getConnection(url, username, password);
            //stmt = con.createStatement();
            Class.forName("com.mysql.cj.jdbc.Driver");
            
        }catch(ClassNotFoundException e){
            e.getMessage();
        }catch(SQLException e){
            e.getMessage();
        }
   
    }
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Enter Reg  ID");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(74, 137, 220));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GENERATE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(268, 268, 268))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        jTextField1.setBorder(BorderFactory.createLineBorder(Color.BLUE));
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        jTextField1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_jTextField1FocusLost

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        jPanel1.setBackground(Color.RED);
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        jPanel1.setBackground(new Color(74,137,220));
    }//GEN-LAST:event_jPanel1MouseExited

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
            enteredRegID = jTextField1.getText();
            //System.out.println(loggedInMail);
//            System.out.println(fetchedOrgName);
//            System.out.println(fetchedOrgAddress);
            
            try{
                pst = con.prepareStatement("SELECT * FROM obtainedmarks WHERE regid = ?");
                pst.setString(1, enteredRegID);
                rs = pst.executeQuery();
                
                if(enteredRegID.equals("")){
                    
                    JOptionPane.showMessageDialog(this, "Please Enter Registration ID");
                }

                else if(rs.next()){
                    
                    JOptionPane.showMessageDialog(this, "Registration ID Matched", "Reg ID Matched Message", JOptionPane.PLAIN_MESSAGE);
                    
                    gNepali = rs.getString("nepali");
                    gEnglish = rs.getString("english");
                    gMaths = rs.getString("maths");
                    gScience = rs.getString("science");
                    gDrawing = rs.getString("drawing");
                    gSerofero = rs.getString("hamroserofero");
                    gLocalSubject = rs.getString("localsubject");
                    gHealth = rs.getString("health");
                    gSocial = rs.getString("social");
                    remark = (rs.getString("remarks")).toUpperCase();
                    ogpa = rs.getString("gpa");
                    
                    //System.out.println("This is Trial 1");
                    pst1 = con.prepareStatement("SELECT * FROM studentpersonaldetails WHERE regid = ?");
                    pst1.setString(1, enteredRegID);
                    rs1 = pst1.executeQuery();
                    if(rs1.next()){
                        fName= (rs1.getString("firstmiddlename")).toUpperCase();
                        lName = (rs1.getString("lastname")).toUpperCase();
                        stdName = fName + " " + lName;
                        stdDOB = rs1.getString("dob");
                        fetchedClass = rs1.getString("grade");
                        //System.out.println("This is Trial 2");
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "No personal information is fetched");
                    }
                    
                    //System.out.println(fetchedClass);
                    
                    
                    //fetaching the organization's data from the database
                    pst2 = con.prepareStatement("SELECT * FROM organizationaldetails WHERE email = ?");
                    pst2.setString(1, loggedInMail);
                    rs2 = pst2.executeQuery();
                    
                    rs2.next();
                        
                        fetchedOrgName = (rs2.getString("orgname")).toUpperCase();
                        fetchedOrgAddress = (rs2.getString("orgaddress")).toUpperCase();
                        yearBS =rs2.getString("yearbs");
                        yearAD =rs2.getString("yearad");
                        
                        //for fetching the image
                        com.mysql.cj.jdbc.Blob image = (com.mysql.cj.jdbc.Blob)rs2.getBlob("orglogo");
                        String path2 = "C:\\Users\\asus\\Documents\\NetBeansProjects\\OurProject\\secondly fetched images\\img.jpg";
                        byte []bytes = image.getBytes(1, (int)image.length());
                        FileOutputStream fos = new FileOutputStream(path2);
                        fos.write(bytes);
                        BufferedImage bi = ImageIO.read(new File(path2));
                        Image img = bi.getScaledInstance(ecdSheet.logoLabel.getWidth(), ecdSheet.logoLabel.getHeight(), Image.SCALE_SMOOTH);
                        ImageIcon scaledImage = new ImageIcon(img);
                        
                        
                        
                        

                    if(fetchedClass.equalsIgnoreCase("ecd")){
                        
                        ecdSheet.setVisible(true);
                        ecdSheet.jLabel5.setText(stdName);
                        ecdSheet.jLabel7.setText(stdDOB);
                        ecdSheet.jLabel41.setText(gNepali);
                        ecdSheet.jLabel42.setText(gEnglish);
                        ecdSheet.jLabel43.setText(gMaths);
                        ecdSheet.jLabel44.setText(gScience);
                        ecdSheet.jLabel46.setText(gDrawing);
                        ecdSheet.jLabel33.setText(remark);
                        ecdSheet.jLabel51.setText(ogpa);
                        ecdSheet.jLabel54.setText(myDate);
                        ecdSheet.jLabel1.setText(fetchedOrgName);
                        ecdSheet.jLabel2.setText(fetchedOrgAddress);
                        ecdSheet.jLabel11.setText(yearBS);
                        ecdSheet.jLabel14.setText(yearAD);
                        ecdSheet.logoLabel.setIcon(scaledImage);
                        Dashboard dash = (Dashboard) SwingUtilities.getWindowAncestor(this);
                        dash.dispose();

//                        System.out.println(orgBase);  
                    }
                    else if(fetchedClass.equals("1")){
                        oneSheet.setVisible(true);
                        oneSheet.jLabel5.setText(stdName);
                        oneSheet.jLabel7.setText(stdDOB);
                        oneSheet.jLabel41.setText(gNepali);
                        oneSheet.jLabel42.setText(gEnglish);
                        oneSheet.jLabel43.setText(gMaths);
                        oneSheet.jLabel44.setText(gScience);
                        oneSheet.jLabel46.setText(gSerofero);
                        oneSheet.jLabel59.setText(gLocalSubject);
                        oneSheet.jLabel47.setText(remark);
                        oneSheet.jLabel51.setText(ogpa);
                        oneSheet.jLabel54.setText(myDate);
                        oneSheet.jLabel1.setText(fetchedOrgName);
                        oneSheet.jLabel2.setText(fetchedOrgAddress);
                        oneSheet.jLabel11.setText(yearBS);
                        oneSheet.jLabel14.setText(yearAD);
                        oneSheet.logoLabel.setIcon(scaledImage);
                        Dashboard dash = (Dashboard) SwingUtilities.getWindowAncestor(this);
                        dash.dispose();
                    }
                    else if(fetchedClass.equals("2")){
                        twoSheet.setVisible(true);
                        twoSheet.jLabel5.setText(stdName);
                        twoSheet.jLabel7.setText(stdDOB);
                        twoSheet.jLabel41.setText(gNepali);
                        twoSheet.jLabel42.setText(gEnglish);
                        twoSheet.jLabel43.setText(gMaths);
                        twoSheet.jLabel44.setText(gScience);
                        twoSheet.jLabel46.setText(gSerofero);
                        twoSheet.jLabel59.setText(gLocalSubject);
                        twoSheet.jLabel49.setText(remark);
                        twoSheet.jLabel51.setText(ogpa);
                        twoSheet.jLabel54.setText(myDate);
                        twoSheet.jLabel1.setText(fetchedOrgName);
                        twoSheet.jLabel2.setText(fetchedOrgAddress);
                        twoSheet.jLabel11.setText(yearBS);
                        twoSheet.jLabel14.setText(yearAD);
                        twoSheet.logoLabel.setIcon(scaledImage);
                        Dashboard dash = (Dashboard) SwingUtilities.getWindowAncestor(this);
                        dash.dispose();
                    }
                    else if(fetchedClass.equals("3")){
                        threeSheet.setVisible(true);
                        threeSheet.jLabel5.setText(stdName);
                        threeSheet.jLabel7.setText(stdDOB);
                        threeSheet.jLabel41.setText(gNepali);
                        threeSheet.jLabel42.setText(gEnglish);
                        threeSheet.jLabel43.setText(gMaths);
                        threeSheet.jLabel44.setText(gScience);
                        threeSheet.jLabel46.setText(gSerofero);
                        threeSheet.jLabel59.setText(gLocalSubject);
                        threeSheet.jLabel47.setText(remark);
                        threeSheet.jLabel51.setText(ogpa);
                        threeSheet.jLabel54.setText(myDate);
                        threeSheet.jLabel1.setText(fetchedOrgName);
                        threeSheet.jLabel2.setText(fetchedOrgAddress);
                        threeSheet.jLabel11.setText(yearBS);
                        threeSheet.jLabel14.setText(yearAD);
                        threeSheet.logoLabel.setIcon(scaledImage);
                        Dashboard dash = (Dashboard) SwingUtilities.getWindowAncestor(this);
                        dash.dispose();
                    }
                    else if(fetchedClass.equals("4")){
                        fourSheet.setVisible(true);
                        fourSheet.jLabel5.setText(stdName);
                        fourSheet.jLabel7.setText(stdDOB);
                        fourSheet.jLabel41.setText(gNepali);
                        fourSheet.jLabel42.setText(gEnglish);
                        fourSheet.jLabel43.setText(gMaths);
                        fourSheet.jLabel44.setText(gScience);
                        fourSheet.jLabel46.setText(gHealth);
                        fourSheet.jLabel59.setText(gSocial);
                        fourSheet.jLabel64.setText(gLocalSubject);
                        fourSheet.jLabel47.setText(remark);
                        fourSheet.jLabel51.setText(ogpa);
                        fourSheet.jLabel54.setText(myDate);
                        fourSheet.jLabel1.setText(fetchedOrgName);
                        fourSheet.jLabel2.setText(fetchedOrgAddress);
                        fourSheet.jLabel11.setText(yearBS);
                        fourSheet.jLabel14.setText(yearAD);
                        fourSheet.logoLabel.setIcon(scaledImage);
                        Dashboard dash = (Dashboard) SwingUtilities.getWindowAncestor(this);
                        dash.dispose();
                    }
                    else if(fetchedClass.equals("5")){
                        fiveSheet.setVisible(true);
                        fiveSheet.jLabel5.setText(stdName);
                        fiveSheet.jLabel7.setText(stdDOB);
                        fiveSheet.jLabel41.setText(gNepali);
                        fiveSheet.jLabel42.setText(gEnglish);
                        fiveSheet.jLabel43.setText(gMaths);
                        fiveSheet.jLabel44.setText(gScience);
                        fiveSheet.jLabel46.setText(gHealth);
                        fiveSheet.jLabel59.setText(gSocial);
                        fiveSheet.jLabel64.setText(gLocalSubject);
                        fiveSheet.jLabel47.setText(remark);
                        fiveSheet.jLabel51.setText(ogpa);
                        fiveSheet.jLabel54.setText(myDate);
                        fiveSheet.jLabel1.setText(fetchedOrgName);
                        fiveSheet.jLabel2.setText(fetchedOrgAddress);
                        fiveSheet.jLabel11.setText(yearBS);
                        fiveSheet.jLabel14.setText(yearAD);
                        fiveSheet.logoLabel.setIcon(scaledImage);
                        Dashboard dash = (Dashboard) SwingUtilities.getWindowAncestor(this);
                        dash.dispose();
                    }
                    else if(fetchedClass.equals("6")){
                        sixSheet.setVisible(true);
                        sixSheet.jLabel5.setText(stdName);
                        sixSheet.jLabel7.setText(stdDOB);
                        sixSheet.jLabel41.setText(gNepali);
                        sixSheet.jLabel42.setText(gEnglish);
                        sixSheet.jLabel43.setText(gMaths);
                        sixSheet.jLabel44.setText(gScience);
                        sixSheet.jLabel46.setText(gHealth);
                        sixSheet.jLabel59.setText(gSocial);
                        sixSheet.jLabel64.setText(gLocalSubject);
                        sixSheet.jLabel47.setText(remark);
                        sixSheet.jLabel51.setText(ogpa);
                        sixSheet.jLabel54.setText(myDate);
                        sixSheet.jLabel1.setText(fetchedOrgName);
                        sixSheet.jLabel2.setText(fetchedOrgAddress);
                        sixSheet.jLabel11.setText(yearBS);
                        sixSheet.jLabel14.setText(yearAD);
                        sixSheet.logoLabel.setIcon(scaledImage);
                        Dashboard dash = (Dashboard) SwingUtilities.getWindowAncestor(this);
                        dash.dispose();
                    }
                    else if(fetchedClass.equals("7")){
                        sevenSheet.setVisible(true);
                        sevenSheet.jLabel5.setText(stdName);
                        sevenSheet.jLabel7.setText(stdDOB);
                        sevenSheet.jLabel41.setText(gNepali);
                        sevenSheet.jLabel42.setText(gEnglish);
                        sevenSheet.jLabel43.setText(gMaths);
                        sevenSheet.jLabel44.setText(gScience);
                        sevenSheet.jLabel46.setText(gHealth);
                        sevenSheet.jLabel59.setText(gSocial);
                        sevenSheet.jLabel64.setText(gLocalSubject);
                        sevenSheet.jLabel47.setText(remark);
                        sevenSheet.jLabel51.setText(ogpa);
                        sevenSheet.jLabel54.setText(myDate);
                        sevenSheet.jLabel1.setText(fetchedOrgName);
                        sevenSheet.jLabel2.setText(fetchedOrgAddress);
                        sevenSheet.jLabel11.setText(yearBS);
                        sevenSheet.jLabel14.setText(yearAD);
                        sevenSheet.logoLabel.setIcon(scaledImage);
                        Dashboard dash = (Dashboard) SwingUtilities.getWindowAncestor(this);
                        dash.dispose();
                    }
                    else {
                        eightSheet.setVisible(true);
                        eightSheet.jLabel5.setText(stdName);
                        eightSheet.jLabel7.setText(stdDOB);
                        eightSheet.jLabel41.setText(gNepali);
                        eightSheet.jLabel42.setText(gEnglish);
                        eightSheet.jLabel43.setText(gMaths);
                        eightSheet.jLabel44.setText(gScience);
                        eightSheet.jLabel46.setText(gHealth);
                        eightSheet.jLabel59.setText(gSocial);
                        eightSheet.jLabel64.setText(gLocalSubject);
                        eightSheet.jLabel47.setText(remark);
                        eightSheet.jLabel51.setText(ogpa);
                        eightSheet.jLabel54.setText(myDate);
                        eightSheet.jLabel1.setText(fetchedOrgName);
                        eightSheet.jLabel2.setText(fetchedOrgAddress);
                        eightSheet.jLabel11.setText(yearBS);
                        eightSheet.jLabel14.setText(yearAD);
                        eightSheet.logoLabel.setIcon(scaledImage);
                        Dashboard dash = (Dashboard) SwingUtilities.getWindowAncestor(this);
                        dash.dispose();
                    }
                    
                }
                else{
                    JOptionPane.showMessageDialog(this, "Invalid Registration ID", "Reg ID Error", JOptionPane.ERROR_MESSAGE);
                }
  
            }catch(SQLException e){
                e.getMessage();
            }catch(FileNotFoundException e){
                e.getMessage();
            }catch(IOException e){
                e.getMessage();
            }
      
        
        
        
        
        
        
        
        
        
        
        

//       ClassECDGradeSheet ecdgs = new ClassECDGradeSheet();
//       Dashboard db = new Dashboard();
//       db.dispose();
//       ecdgs.setVisible(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        char c = evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)){
            jTextField1.setEditable(true);
        }
        else{
            jTextField1.setEditable(false);
        }
    }//GEN-LAST:event_jTextField1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
